Threw exception correctly
Completed - no errors
